#ifndef BOOTLOADER_USB_DESCRIPTORS_H_
#define BOOTLOADER_USB_DESCRIPTORS_H_

#include "updater_shared.h"

#define USB_VID KBHE_USB_VID
#define USB_PID KBHE_UPDATER_USB_PID
#define USB_BCD 0x0200

#define USB_RHPORT_HS 1u

#define EPNUM_UPDATER_OUT 0x01
#define EPNUM_UPDATER_IN 0x01
#define HID_EP_SIZE 64
#define UPDATER_POLL_INTERVAL 4

enum {
  STRID_LANGID = 0,
  STRID_MANUFACTURER,
  STRID_PRODUCT,
  STRID_SERIAL,
  STRID_UPDATER,
};

enum {
  HID_ITF_UPDATER = 0,
};

#endif /* BOOTLOADER_USB_DESCRIPTORS_H_ */
