export const AllKeys = [

  // ---------- Letters ----------
  { id: "a", label: "A", value: "KeyA", width: 1, type: "Letters" },
  { id: "b", label: "B", value: "KeyB", width: 1, type: "Letters" },
  { id: "c", label: "C", value: "KeyC", width: 1, type: "Letters" },
  { id: "d", label: "D", value: "KeyD", width: 1, type: "Letters" },
  { id: "e", label: "E", value: "KeyE", width: 1, type: "Letters" },
  { id: "f", label: "F", value: "KeyF", width: 1, type: "Letters" },
  { id: "g", label: "G", value: "KeyG", width: 1, type: "Letters" },
  { id: "h", label: "H", value: "KeyH", width: 1, type: "Letters" },
  { id: "i", label: "I", value: "KeyI", width: 1, type: "Letters" },
  { id: "j", label: "J", value: "KeyJ", width: 1, type: "Letters" },
  { id: "k", label: "K", value: "KeyK", width: 1, type: "Letters" },
  { id: "l", label: "L", value: "KeyL", width: 1, type: "Letters" },
  { id: "m", label: "M", value: "KeyM", width: 1, type: "Letters" },
  { id: "n", label: "N", value: "KeyN", width: 1, type: "Letters" },
  { id: "o", label: "O", value: "KeyO", width: 1, type: "Letters" },
  { id: "p", label: "P", value: "KeyP", width: 1, type: "Letters" },
  { id: "q", label: "Q", value: "KeyQ", width: 1, type: "Letters" },
  { id: "r", label: "R", value: "KeyR", width: 1, type: "Letters" },
  { id: "s", label: "S", value: "KeyS", width: 1, type: "Letters" },
  { id: "t", label: "T", value: "KeyT", width: 1, type: "Letters" },
  { id: "u", label: "U", value: "KeyU", width: 1, type: "Letters" },
  { id: "v", label: "V", value: "KeyV", width: 1, type: "Letters" },
  { id: "w", label: "W", value: "KeyW", width: 1, type: "Letters" },
  { id: "x", label: "X", value: "KeyX", width: 1, type: "Letters" },
  { id: "y", label: "Y", value: "KeyY", width: 1, type: "Letters" },
  { id: "z", label: "Z", value: "KeyZ", width: 1, type: "Letters" },

  // ---------- Function ----------
  { id: "f1", label: "F1", value: "F1", width: 1, type: "Function" },
  { id: "f2", label: "F2", value: "F2", width: 1, type: "Function" },
  { id: "f3", label: "F3", value: "F3", width: 1, type: "Function" },
  { id: "f4", label: "F4", value: "F4", width: 1, type: "Function" },
  { id: "f5", label: "F5", value: "F5", width: 1, type: "Function" },
  { id: "f6", label: "F6", value: "F6", width: 1, type: "Function" },
  { id: "f7", label: "F7", value: "F7", width: 1, type: "Function" },
  { id: "f8", label: "F8", value: "F8", width: 1, type: "Function" },
  { id: "f9", label: "F9", value: "F9", width: 1, type: "Function" },
  { id: "f10", label: "F10", value: "F10", width: 1, type: "Function" },
  { id: "f11", label: "F11", value: "F11", width: 1, type: "Function" },
  { id: "f12", label: "F12", value: "F12", width: 1, type: "Function" },
  { id: "f13", label: "F13", value: "F13", width: 1, type: "Function" },
  { id: "f14", label: "F14", value: "F14", width: 1, type: "Function" },
  { id: "f15", label: "F15", value: "F15", width: 1, type: "Function" },
  { id: "f16", label: "F16", value: "F16", width: 1, type: "Function" },
  { id: "f17", label: "F17", value: "F17", width: 1, type: "Function" },
  { id: "f18", label: "F18", value: "F18", width: 1, type: "Function" },
  { id: "f19", label: "F19", value: "F19", width: 1, type: "Function" },
  { id: "f20", label: "F20", value: "F20", width: 1, type: "Function" },
  { id: "f21", label: "F21", value: "F21", width: 1, type: "Function" },
  { id: "f22", label: "F22", value: "F22", width: 1, type: "Function" },
  { id: "f23", label: "F23", value: "F23", width: 1, type: "Function" },
  { id: "f24", label: "F24", value: "F24", width: 1, type: "Function" },

  // ---------- Modifiers ----------
  { id: "shift", label: "Shift L", value: "ShiftLeft", width: 1, type: "Modifiers" },
  { id: "shift_r", label: "Shift R", value: "ShiftRight", width: 1, type: "Modifiers" },
  { id: "ctrl", label: "Ctrl L", value: "ControlLeft", width: 1, type: "Modifiers" },
  { id: "ctrl_r", label: "Ctrl R", value: "ControlRight", width: 1, type: "Modifiers" },
  { id: "alt", label: "Alt L", value: "AltLeft", width: 1, type: "Modifiers" },
  { id: "altgr", label: "AltGr", value: "AltRight", width: 1, type: "Modifiers" },
  { id: "win", label: "Win L", value: "MetaLeft", width: 1, type: "Modifiers" },
  { id: "win_r", label: "Win R", value: "MetaRight", width: 1, type: "Modifiers" },
  { id: "fn", label: "Fn", value: "Fn", width: 1, type: "Modifiers" },
  { id: "capslock", label: "Caps", value: "CapsLock", width: 1, type: "Modifiers" },

  // ---------- Navigation ----------
  { id: "up", label: "↑", value: "ArrowUp", width: 1, type: "Navigation" },
  { id: "down", label: "↓", value: "ArrowDown", width: 1, type: "Navigation" },
  { id: "left", label: "←", value: "ArrowLeft", width: 1, type: "Navigation" },
  { id: "right", label: "→", value: "ArrowRight", width: 1, type: "Navigation" },
  { id: "pgup", label: "PgUp", value: "PageUp", width: 1, type: "Navigation" },
  { id: "pgdn", label: "PgDn", value: "PageDown", width: 1, type: "Navigation" },
  { id: "home", label: "Home", value: "Home", width: 1, type: "Navigation" },
  { id: "end", label: "End", value: "End", width: 1, type: "Navigation" },
  { id: "insert", label: "Insert", value: "Insert", width: 1, type: "Navigation" },

  // ---------- Numbers ----------
  { id: "1", label: "&", value: "Digit1", width: 1, type: "Numbers" },
  { id: "2", label: "é", value: "Digit2", width: 1, type: "Numbers" },
  { id: "3", label: "\"", value: "Digit3", width: 1, type: "Numbers" },
  { id: "4", label: "'", value: "Digit4", width: 1, type: "Numbers" },
  { id: "5", label: "(", value: "Digit5", width: 1, type: "Numbers" },
  { id: "6", label: "-", value: "Digit6", width: 1, type: "Numbers" },
  { id: "7", label: "è", value: "Digit7", width: 1, type: "Numbers" },
  { id: "8", label: "_", value: "Digit8", width: 1, type: "Numbers" },
  { id: "9", label: "ç", value: "Digit9", width: 1, type: "Numbers" },
  { id: "0", label: "à", value: "Digit0", width: 1, type: "Numbers" },

  // ---------- Numpad ----------
  { id: "num0", label: "Num 0", value: "Numpad0", width: 1, type: "Numpad" },
  { id: "num1", label: "Num 1", value: "Numpad1", width: 1, type: "Numpad" },
  { id: "num2", label: "Num 2", value: "Numpad2", width: 1, type: "Numpad" },
  { id: "num3", label: "Num 3", value: "Numpad3", width: 1, type: "Numpad" },
  { id: "num4", label: "Num 4", value: "Numpad4", width: 1, type: "Numpad" },
  { id: "num5", label: "Num 5", value: "Numpad5", width: 1, type: "Numpad" },
  { id: "num6", label: "Num 6", value: "Numpad6", width: 1, type: "Numpad" },
  { id: "num7", label: "Num 7", value: "Numpad7", width: 1, type: "Numpad" },
  { id: "num8", label: "Num 8", value: "Numpad8", width: 1, type: "Numpad" },
  { id: "num9", label: "Num 9", value: "Numpad9", width: 1, type: "Numpad" },
  { id: "num_add", label: "Num +", value: "NumpadAdd", width: 1, type: "Numpad" },
  { id: "num_sub", label: "Num -", value: "NumpadSubtract", width: 1, type: "Numpad" },
  { id: "num_mul", label: "Num *", value: "NumpadMultiply", width: 1, type: "Numpad" },
  { id: "num_div", label: "Num /", value: "NumpadDivide", width: 1, type: "Numpad" },
  { id: "num_dec", label: "Num .", value: "NumpadDecimal", width: 1, type: "Numpad" },
  { id: "num_enter", label: "Num Enter", value: "NumpadEnter", width: 1, type: "Numpad" },
  { id: "numlock", label: "NumLock", value: "NumLock", width: 1, type: "Numpad" },

  // ---------- Special ----------
  { id: "esc", label: "Esc", value: "Escape", width: 1, type: "Special" },
  { id: "enter", label: "Enter", value: "Enter", width: 1, type: "Special" },
  { id: "space", label: "Space", value: "Space", width: 1, type: "Special" },
  { id: "backspace", label: "Bcks", value: "Backspace", width: 1, type: "Special" },
  { id: "tab", label: "Tab", value: "Tab", width: 1, type: "Special" },
  { id: "del", label: "Del", value: "Delete", width: 1, type: "Special" },
  { id: "printscreen", label: "PrtSc", value: "PrintScreen", width: 1, type: "Special" },
  { id: "scrolllock", label: "ScrLk", value: "ScrollLock", width: 1, type: "Special" },
  { id: "pause", label: "Pause", value: "Pause", width: 1, type: "Special" },
  { id: "contextmenu", label: "Menu", value: "ContextMenu", width: 1, type: "Special" },

  // ---------- Media ----------
  { id: "media_play", label: "Play/Pause", value: "MediaPlayPause", width: 1, type: "Media" },
  { id: "media_stop", label: "Stop", value: "MediaStop", width: 1, type: "Media" },
  { id: "media_next", label: "Next", value: "MediaTrackNext", width: 1, type: "Media" },
  { id: "media_prev", label: "Prev", value: "MediaTrackPrevious", width: 1, type: "Media" },
  { id: "media_mute", label: "Mute", value: "AudioVolumeMute", width: 1, type: "Media" },
  { id: "media_volup", label: "Vol +", value: "AudioVolumeUp", width: 1, type: "Media" },
  { id: "media_voldown", label: "Vol -", value: "AudioVolumeDown", width: 1, type: "Media" },

  // ---------- Symbols ----------
  { id: "grave", label: "²", value: "Backquote", width: 1, type: "Symbols" },
  { id: "minus", label: ")", value: "Minus", width: 1, type: "Symbols" },
  { id: "equal", label: "=", value: "Equal", width: 1, type: "Symbols" },
  { id: "lbracket", label: "^", value: "BracketLeft", width: 1, type: "Symbols" },
  { id: "rbracket", label: "$", value: "BracketRight", width: 1, type: "Symbols" },
  { id: "backslash", label: "*", value: "Backslash", width: 1, type: "Symbols" },
  { id: "ù", label: "Ù", value: "Quote", width: 1, type: "Symbols" },
  { id: "comma", label: ",", value: "Comma", width: 1, type: "Symbols" },
  { id: "semicolon", label: ";", value: "Semicolon", width: 1, type: "Symbols" },
  { id: "colon", label: ":", value: "Period", width: 1, type: "Symbols" },
  { id: "excl", label: "!", value: "Slash", width: 1, type: "Symbols" },
  { id: "sign", label: "<", value: "IntlBackslash", width: 1, type: "Symbols" },
]


{/*export const AllKeys = [
  // ---------- Function Row ----------
  { id: "esc", label: "Esc", value: "Escape", width: 1, type: "Extended" },
  { id: "f1", label: "F1", value: "F1", width: 1, type: "Basic" },
  { id: "f2", label: "F2", value: "F2", width: 1, type: "Basic" },
  { id: "f3", label: "F3", value: "F3", width: 1, type: "Basic" },
  { id: "f4", label: "F4", value: "F4", width: 1, type: "Basic" },
  { id: "f5", label: "F5", value: "F5", width: 1, type: "Basic" },
  { id: "f6", label: "F6", value: "F6", width: 1, type: "Basic" },
  { id: "f7", label: "F7", value: "F7", width: 1, type: "Basic" },
  { id: "f8", label: "F8", value: "F8", width: 1, type: "Basic" },
  { id: "f9", label: "F9", value: "F9", width: 1, type: "Basic" },
  { id: "f10", label: "F10", value: "F10", width: 1, type: "Basic" },
  { id: "f11", label: "F11", value: "F11", width: 1, type: "Basic" },
  { id: "f12", label: "F12", value: "F12", width: 1, type: "Basic" },
  { id: "del", label: "Del", value: "Delete", width: 1, type: "Extended" },

  // ---------- Number Row ----------
  { id: "grave", label: "²", value: "Backquote", width: 1, type: "Basic" },
  { id: "1", label: "&", value: "Digit1", width: 1, type: "Basic" },
  { id: "2", label: "é", value: "Digit2", width: 1, type: "Basic" },
  { id: "3", label: "\"", value: "Digit3", width: 1, type: "Basic" },
  { id: "4", label: "'", value: "Digit4", width: 1, type: "Basic" },
  { id: "5", label: "(", value: "Digit5", width: 1, type: "Basic" },
  { id: "6", label: "-", value: "Digit6", width: 1, type: "Basic" },
  { id: "7", label: "è", value: "Digit7", width: 1, type: "Basic" },
  { id: "8", label: "_", value: "Digit8", width: 1, type: "Basic" },
  { id: "9", label: "ç", value: "Digit9", width: 1, type: "Basic" },
  { id: "0", label: "à", value: "Digit0", width: 1, type: "Basic" },
  { id: "minus", label: ")", value: "Minus", width: 1, type: "Basic" },
  { id: "equal", label: "=", value: "Equal", width: 1, type: "Basic" },
  { id: "backspace", label: "Backspace", value: "Backspace", width: 1, type: "Extended" },
  { id: "pgup", label: "PgUp", value: "PageUp", width: 1, type: "Extended" },

  // ---------- QWERTY Row ----------
  { id: "tab", label: "Tab", value: "Tab", width: 1, type: "Extended" },
  { id: "a", label: "A", value: "KeyA", width: 1, type: "Basic" },
  { id: "z", label: "Z", value: "KeyZ", width: 1, type: "Basic" },
  { id: "e", label: "E", value: "KeyE", width: 1, type: "Basic" },
  { id: "r", label: "R", value: "KeyR", width: 1, type: "Basic" },
  { id: "t", label: "T", value: "KeyT", width: 1, type: "Basic" },
  { id: "y", label: "Y", value: "KeyY", width: 1, type: "Basic" },
  { id: "u", label: "U", value: "KeyU", width: 1, type: "Basic" },
  { id: "i", label: "I", value: "KeyI", width: 1, type: "Basic" },
  { id: "o", label: "O", value: "KeyO", width: 1, type: "Basic" },
  { id: "p", label: "P", value: "KeyP", width: 1, type: "Basic" },
  { id: "lbracket", label: "^", value: "BracketLeft", width: 1, type: "Basic" },
  { id: "rbracket", label: "$", value: "BracketRight", width: 1, type: "Basic" },
  { id: "enter", label: "Enter", value: "Enter", width: 1, type: "Extended" },
  { id: "pgdn", label: "PgDn", value: "PageDown", width: 1, type: "Extended" },

  // ---------- Home Row ----------
  { id: "capslock", label: "Caps", value: "CapsLock", width: 1, type: "Extended" },
  { id: "q", label: "Q", value: "KeyQ", width: 1, type: "Basic" },
  { id: "s", label: "S", value: "KeyS", width: 1, type: "Basic" },
  { id: "d", label: "D", value: "KeyD", width: 1, type: "Basic" },
  { id: "f", label: "F", value: "KeyF", width: 1, type: "Basic" },
  { id: "g", label: "G", value: "KeyG", width: 1, type: "Basic" },
  { id: "h", label: "H", value: "KeyH", width: 1, type: "Basic" },
  { id: "j", label: "J", value: "KeyJ", width: 1, type: "Basic" },
  { id: "k", label: "K", value: "KeyK", width: 1, type: "Basic" },
  { id: "l", label: "L", value: "KeyL", width: 1, type: "Basic" },
  { id: "m", label: "M", value: "KeyM", width: 1, type: "Basic" },
  { id: "ù", label: "Ù", value: "Quote", width: 1, type: "Basic" },
  { id: "backslash", label: "*", value: "Backslash", width: 1, type: "Basic" },
  { id: "home", label: "Home", value: "Home", width: 1, type: "Extended" },

  // ---------- Shift Row ----------
  { id: "shift", label: "Shift", value: "ShiftLeft", width: 1, type: "Extended" },
  { id: "sign", label: "<", value: "sign", width: 1, type: "Basic" },
  { id: "w", label: "W", value: "KeyW", width: 1, type: "Basic" },
  { id: "x", label: "X", value: "KeyX", width: 1, type: "Basic" },
  { id: "c", label: "C", value: "KeyC", width: 1, type: "Basic" },
  { id: "v", label: "V", value: "KeyV", width: 1, type: "Basic" },
  { id: "b", label: "B", value: "KeyB", width: 1, type: "Basic" },
  { id: "n", label: "N", value: "KeyN", width: 1, type: "Basic" },
  { id: "comma", label: ",", value: "Comma", width: 1, type: "Basic" },
  { id: "semicolon", label: ";", value: "Semicolon", width: 1, type: "Basic" },
  { id: "colon", label: ":", value: "Period", width: 1, type: "Basic" },
  { id: "excl", label: "!", value: "Slash", width: 1, type: "Basic" },
  { id: "shift_r", label: "Shift R", value: "ShiftRight", width: 1, type: "Extended" },
  { id: "up", label: "↑", value: "ArrowUp", width: 1, type: "Extended" },

  // ---------- Bottom Row ----------
  { id: "ctrl", label: "Ctrl", value: "ControlLeft", width: 1, type: "Extended" },
  { id: "win", label: "Win", value: "win", width: 1, type: "Extended" },
  { id: "alt", label: "Alt", value: "AltLeft", width: 1, type: "Extended" },
  { id: "space", label: "Space", value: "Space", width: 1, type: "Basic" },
  { id: "altgr", label: "AltGr", value: "AltRight", width: 1, type: "Extended" },
  { id: "fn", label: "Fn", value: "Fn", width: 1, type: "Extended" },
  { id: "ctrl_r", label: "Ctrl R", value: "ControlRight", width: 1, type: "Extended" },
  { id: "left", label: "←", value: "ArrowLeft", width: 1, type: "Extended" },
  { id: "down", label: "↓", value: "ArrowDown", width: 1, type: "Extended" },
  { id: "right", label: "→", value: "ArrowRight", width: 1, type: "Extended" },
]
*/}

